
################################################################################
###                  Running FredBoat with docker-compose
################################################################################
###
### Use a proper text editor like Sublime when editing this file
### Do not use tab characters in this file, only spaces are allowed. Don't add or delete unnecessary spaces.
### More information on correctly formatting yaml files: http://www.yaml.org/start.html
###
### For further information on running FredBoat visit https://fredboat.com/docs/selfhosting or the #selfhosting channel
### on the FredBoat Hangout Discord server: https://discord.gg/cgPFW4q


version: '3' # This is not the FredBoat version, do not touch this line.
services:

  ################################################################################
  ##                               Database
  ################################################################################
  db:
    image: fredboat/postgres
    #build: ./FredBoat/docker/database/ #useful alternative for developers
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    # WINDOWS ONLY: if you are running under windows you need to comment out the following two lines:
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    # WINDOWS ONLY: if you are running under windows and want to take manual backups of the database
    # via a docker volume, uncomment the following two lines and read the snippet at the bottom of this file
    #volumes:
      #- postgres-data-volume:/var/lib/postgresql/data


  ################################################################################
  ##                               FredBoat
  ################################################################################
  bot:
    # pick one of these: stable or dev
    # dev receives more frequent updates than stable but may have more bugs / things breaking
    # versions (example: v2) receive continous non-breaking (best effort) updates via watchtower. switching between versions
    # (example: going from v2 to v3) usually requires manual migration. what exactly is needed is published on the
    # FredBoat selfhosting website and/or the selfhosters channel (see top of this file for how to get to these places)
    image: fredboat/fredboat:stable-v2
    #image: fredboat/fredboat:dev-v2
    #build: ./FredBoat #useful alternative for developers

    restart: on-failure:3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - db
    ports:
      - 1356:1356
    volumes:
      - ./config.yaml:/opt/FredBoat/config.yaml
      - ./credentials.yaml:/opt/FredBoat/credentials.yaml
      - ./logs:/opt/FredBoat/logs
      - ./music_persistence:/opt/FredBoat/music_persistence
      # Local audio files (dev branch only currently)
      # If your music directory looks like this: /home/user/music/directory/rickroll.mp3 or C:\Users\user\Music\rickroll.mp3
      # you will be able to play that file with this command: <<play file://music/rickroll.mp3
      # Linux example:
      #- /home/your_user_name/music:/opt/FredBoat/music
      # Windows example:
      #- C:\Users\your_user_name\Music:/opt/FredBoat/music

    # Need a bigger memory size or any other custom JVM args? uncomment and edit the line below accordingly
    #entrypoint: java -Xmx128m -jar FredBoat.jar


  ################################################################################
  ##                         Automatic updates
  ################################################################################
  # if you want automatic updates, uncomment the watchtower lines below

  #watchtower:
  #  image: v2tec/watchtower
  #  restart: on-failure:3
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --cleanup --label-enable --interval 300 #seconds


  ################################################################################
  ##                         Windows stuff
  ################################################################################

# WINDOWS ONLY: If you are running on Windows and want to be able to backup the postgres data volume, run
#
#   docker volume create --name postgres-data-volume -d local
#
# and uncomment the following lines:
# See also the WINDOWS ONLY hints in the database section

#volumes:
#  postgres-data-volume:
#    external: true
